on: 
  push:
    branches:
      - Develop

name: 🚀 Deploy Desenvolvimento
jobs:
  web-deploy:
    name: 🎉 DDeploy Desenvolvimento
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        port: ${{ secrets.ftp_port }}
        server-dir: sistemapallas/develop/